#!/bin/bash
# ⚠️  OUTDATED — DO NOT RUN. This script generated the initial language pages
# under the old SunriseTi.me branding. The pages in ar/ bn/ de/ es/ fr/ hi/ id/
# ja/ ms/ pt/ ru/ tr/ ur/ zh/ have since been rebranded to WhenSunrise.com and
# edited in place (hreflang, OG tags, privacy links, GA). Running this script
# would destroy those changes. Kept for reference only.

# Turkish
cat > tr/index.html << 'EOF'
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gün Doğumu ve Gün Batımı | Namaz Vakitleri | SunriseTi.me</title>
    <meta name="description" content="Doğru gün doğumu, gün batımı ve namaz vakitlerini alın. İmsak, Güneş, Öğle, İkindi, Akşam, Yatsı.">
    <link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Ccircle cx='50' cy='50' r='40' fill='%23FFD700'/%3E%3C/svg%3E">
    <script src="https://cdn.tailwindcss.com"></script>
    <style>* { font-family: 'Inter', sans-serif; } .sky-day { background: linear-gradient(180deg, #2193b0 0%, #6dd5ed 50%, #87CEEB 100%); } .glass { background: rgba(255, 255, 255, 0.1); backdrop-filter: blur(10px); border: 1px solid rgba(255, 255, 255, 0.2); } .glass-dark { background: rgba(0, 0, 0, 0.2); } .day-progress { background: linear-gradient(90deg, #ffd700 0%, #ff8c00 50%, #ff6b6b 100%); } @keyframes pulse-glow { 0%, 100% { box-shadow: 0 0 40px rgba(255, 200, 50, 0.6); } 50% { box-shadow: 0 0 80px rgba(255, 200, 50, 0.9); } } .sun-glow { animation: pulse-glow 2s ease-in-out infinite; } @keyframes float { 0%, 100% { transform: translateY(0); } 50% { transform: translateY(-10px); } } .float { animation: float 3s ease-in-out infinite; } .autocomplete-results { position: absolute; top: 100%; left: 0; right: 0; z-index: 9999; max-height: 300px; overflow-y: auto; background: rgba(15, 23, 42, 0.98); } .autocomplete-item { padding: 12px 16px; cursor: pointer; } .autocomplete-item:hover { background: rgba(255,255,255,0.15); }</style>
</head>
<body class="min-h-screen sky-day text-white" id="body">
    <div class="relative z-10">
        <header class="py-4 px-4"><div class="max-w-5xl mx-auto flex items-center justify-between"><a href="/tr/" class="flex items-center gap-2"><div class="w-10 h-10 rounded-full bg-gradient-to-br from-yellow-300 to-orange-500 sun-glow"></div><span class="text-xl font-bold">SunriseTi<span class="text-yellow-300">.me</span></span></a><div class="relative group"><button class="text-white/70 hover:text-white text-sm">🇹🇷</button><div class="absolute right-0 mt-2 w-36 bg-slate-800/95 rounded-lg opacity-0 invisible group-hover:opacity-100 group-hover:visible z-50"><a href="/" class="block px-3 py-2 text-sm hover:bg-white/10">🇺🇸 English</a><a href="/ar/" class="block px-3 py-2 text-sm hover:bg-white/10">🇸🇦 العربية</a><a href="/tr/" class="block px-3 py-2 text-sm bg-white/5">🇹🇷 Türkçe</a><a href="/de/" class="block px-3 py-2 text-sm hover:bg-white/10">🇩🇪 Deutsch</a></div></div></div></header>
        <main class="px-4 pb-12"><div class="max-w-5xl mx-auto">
            <section class="text-center py-6">
                <div class="relative inline-block mb-4"><div class="w-28 h-28 rounded-full bg-gradient-to-br from-yellow-200 via-yellow-400 to-orange-500 sun-glow float mx-auto"></div><div class="absolute inset-0 flex items-center justify-center"><span class="text-4xl" id="sunMoonEmoji">☀️</span></div></div>
                <div class="mb-3 relative max-w-md mx-auto"><div class="inline-flex items-center gap-2 glass px-4 py-2 rounded-full w-full"><svg class="w-5 h-5 text-yellow-300" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"/></svg><input type="text" id="locationSearch" class="bg-transparent border-none outline-none flex-1 text-center placeholder-white/50" placeholder="Şehir ara..."><button id="detectLocation" class="text-yellow-300"><svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8"/></svg></button></div><div id="autocompleteResults" class="autocomplete-results hidden rounded-lg mt-2"></div></div>
                <p class="text-white/60 text-sm mb-4" id="currentDate">Yükleniyor...</p>
                <div class="grid grid-cols-2 gap-3 max-w-md mx-auto mb-6"><div class="glass rounded-2xl p-4 text-center"><div class="text-3xl mb-1">🌅</div><p class="text-white/60 text-xs mb-1">GÜN DOĞUMU</p><p class="text-2xl font-bold text-yellow-300" id="sunriseTime">--:--</p></div><div class="glass rounded-2xl p-4 text-center"><div class="text-3xl mb-1">🌇</div><p class="text-white/60 text-xs mb-1">GÜN BATIMI</p><p class="text-2xl font-bold text-orange-400" id="sunsetTime">--:--</p></div></div>
                <div class="max-w-md mx-auto mb-6"><div class="flex justify-between text-xs text-white/60 mb-1"><span>Gün İlerlemesi</span><span id="dayProgressPercent">0%</span></div><div class="h-2 bg-white/10 rounded-full overflow-hidden"><div class="h-full day-progress rounded-full" id="dayProgressBar" style="width: 0%"></div></div></div>
            </section>
            <section class="glass rounded-2xl p-5 mb-6"><div class="flex items-center justify-between mb-4"><h2 class="text-lg font-semibold">🕌 Namaz Vakitleri</h2><select id="prayerMethod" class="bg-white/10 border border-white/20 rounded-lg px-2 py-1 text-sm"><option value="MWL">Diyanet</option><option value="ISNA">ISNA</option><option value="MAKKAH">Ümmül Kura</option></select></div><div class="grid grid-cols-3 md:grid-cols-6 gap-2" id="prayerTimesGrid"></div><p class="text-white/40 text-xs mt-3 text-center" id="nextPrayerInfo">Yükleniyor...</p></section>
            <section class="glass rounded-2xl p-5 mb-6"><h2 class="text-lg font-semibold mb-4">🌙 Ay Evresi</h2><div class="flex flex-col md:flex-row items-center gap-6"><div class="text-center"><div class="text-6xl mb-2" id="moonEmoji">🌕</div><p class="font-semibold" id="moonPhaseName">Dolunay</p><p class="text-white/60 text-sm" id="moonIllumination">%100 aydınlık</p></div><div class="flex-1 grid grid-cols-2 gap-4"><div class="glass-dark rounded-xl p-3 text-center"><p class="text-white/60 text-xs">Sonraki Dolunay</p><p class="font-semibold" id="nextFullMoon">--</p></div><div class="glass-dark rounded-xl p-3 text-center"><p class="text-white/60 text-xs">Sonraki Yeni Ay</p><p class="font-semibold" id="nextNewMoon">--</p></div><div class="glass-dark rounded-xl p-3 text-center"><p class="text-white/60 text-xs">Ay Doğuşu</p><p class="font-semibold" id="moonrise">--:--</p></div><div class="glass-dark rounded-xl p-3 text-center"><p class="text-white/60 text-xs">Ay Batışı</p><p class="font-semibold" id="moonset">--:--</p></div></div></div></section>
            <section class="grid md:grid-cols-4 gap-3 mb-6"><div class="glass rounded-2xl p-4"><div class="flex items-center gap-3"><div class="w-10 h-10 rounded-full bg-yellow-500/20 flex items-center justify-center">⏱️</div><div><p class="text-white/60 text-xs">Gün Uzunluğu</p><p class="text-lg font-semibold" id="dayLength">--s --d</p></div></div></div><div class="glass rounded-2xl p-4"><div class="flex items-center gap-3"><div class="w-10 h-10 rounded-full bg-orange-500/20 flex items-center justify-center">🔆</div><div><p class="text-white/60 text-xs">Öğle Vakti</p><p class="text-lg font-semibold" id="solarNoon">--:--</p></div></div></div><div class="glass rounded-2xl p-4"><div class="flex items-center gap-3"><div class="w-10 h-10 rounded-full bg-amber-500/20 flex items-center justify-center">📸</div><div><p class="text-white/60 text-xs">Altın Saat (Sabah)</p><p class="text-lg font-semibold" id="goldenMorning">--:--</p></div></div></div><div class="glass rounded-2xl p-4"><div class="flex items-center gap-3"><div class="w-10 h-10 rounded-full bg-red-500/20 flex items-center justify-center">🌄</div><div><p class="text-white/60 text-xs">Altın Saat (Akşam)</p><p class="text-lg font-semibold" id="goldenEvening">--:--</p></div></div></div></section>
            <section class="glass rounded-2xl p-5 mb-6"><h2 class="text-lg font-semibold mb-4">📆 7 Günlük Tahmin</h2><div class="overflow-x-auto"><div class="grid grid-cols-7 gap-2 min-w-[560px]" id="forecast"></div></div></section>
            <section class="glass rounded-2xl p-5"><h2 class="text-lg font-semibold mb-4">🌍 Popüler Şehirler</h2><div class="flex flex-wrap gap-2"><button class="city-btn glass-dark px-3 py-2 rounded-lg text-sm hover:bg-white/10" data-lat="41.0082" data-lng="28.9784">İstanbul</button><button class="city-btn glass-dark px-3 py-2 rounded-lg text-sm hover:bg-white/10" data-lat="39.9334" data-lng="32.8597">Ankara</button><button class="city-btn glass-dark px-3 py-2 rounded-lg text-sm hover:bg-white/10" data-lat="38.4192" data-lng="27.1287">İzmir</button><button class="city-btn glass-dark px-3 py-2 rounded-lg text-sm hover:bg-white/10" data-lat="21.3891" data-lng="39.8579">Mekke</button><button class="city-btn glass-dark px-3 py-2 rounded-lg text-sm hover:bg-white/10" data-lat="51.5074" data-lng="-0.1278">Londra</button></div></section>
        </div></main>
        <footer class="py-6 px-4 border-t border-white/10"><div class="max-w-5xl mx-auto text-center text-white/40 text-sm"><p>© 2026 SunriseTi.me — Dünya genelinde gün doğumu, gün batımı ve namaz vakitleri</p></div></footer>
    </div>
    <script src="../app.js"></script><script src="../cities.js"></script><script src="../moon.js"></script><script src="../prayer.js"></script><script src="../init.js"></script>
</body>
</html>
EOF

echo "Turkish done"
